version: '3.8'
name: microservice-app
services:
  front:
    image: guillermopalacios/angular_mechanic
    container_name: front-app
    ports:
      - "4200:80"
    networks:
      - mechanic-net
    
  discovery:
    image: guillermopalacios/microservice-app-discovery-server
    container_name: discovery-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
    ports:
      - "8761:8761"
    networks:
      - mechanic-net

  gateway:
    image: guillermopalacios/microservice-app-api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      URL_FRONT: http://front:80
    networks:
      - mechanic-net

  main:
    image: guillermopalacios/microservice-app-principal-service
    container_name: principal-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/principal_db
      URL_FRONT: http://front:80
    depends_on:
      - db
      - gateway
      - discovery
    networks:
      - principal-net
      - mechanic-net

  order:
    image: guillermopalacios/microservice-app-order-service
    container_name: order-service
    depends_on:
      - gateway
      - discovery
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      MONGODB_URI: mongodb+srv://nothi:129837465lg@cluster0.na3zkcc.mongodb.net/work_order_db?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - mechanic-net

  db:
    restart: always
    image: guillermopalacios/microservice-app-mysql-main
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 129837465lg
      MYSQL_DATABASE: principal_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - principal-net

volumes:
  mysql_data:

networks:
  mechanic-net:
    driver: bridge
  principal-net:
    driver: bridge