version: '3.8'
name: microservice-app

services:
  discovery:
    image: guillermopalacios/microservice-app-discovery-server
    container_name: discovery-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
    ports:
      - "8761:8761"
    networks:
      - mechanic-net

  gateway:
    image: guillermopalacios/microservice-app-api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      URL_FRONT: https://imechanic.netlify.app
    networks:
      - mechanic-net

  main:
    image: guillermopalacios/microservice-app-principal-service
    container_name: principal-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/principal_db
      URL_FRONT: https://imechanic.netlify.app
    depends_on:
      - db
      - gateway
      - discovery
    networks:
      - mechanic-net

  order:
    image: guillermopalacios/microservice-app-order-service
    container_name: order-service
    depends_on:
      - gateway
      - discovery
      - mongodb
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      MONGODB_URI: mongodb://root:129837465lg@mongodb:27017/work_order_db?authSource=admin
    networks:
      - mechanic-net

  db:
    restart: always
    image: guillermopalacios/microservice-app-mysql-main
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 129837465lg
      MYSQL_DATABASE: principal_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mechanic-net

  mongodb:
    restart: always
    image: guillermopalacios/microservice-app-mongodb-order
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 129837465lg
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mechanic-net

volumes:
  mysql_data:
  mongo_data:

networks:
  mechanic-net:
    driver: bridge