version: '3.8'
name: microservice_app
services:
  angular_front:
    image: guillermopalacios/angular_mechanic
    container_name: front-app
    ports:
      - "4200:80"
    networks:
      - mechanic-net
    
  discovery_server:
    image: guillermopalacios/microservice_mechanic_discovery_server
    container_name: discovery-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery_server:8761/eureka
    ports:
      - "8761:8761"
    depends_on:
      - angular_front
    networks:
      - mechanic-net

  api_gateway:
    image: guillermopalacios/microservice_mechanic_api_gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery_server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery_server:8761/eureka
    networks:
      - mechanic-net

  principal_service:
    image: guillermopalacios/microservice_mechanic_principal_service
    container_name: principal-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery_server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db_principal:3306/principal_db
    depends_on:
      - db_principal
      - discovery_server
    networks:
      - principal-net
      - mechanic-net

  order_service:
    image: guillermopalacios/microservice_mechanic_order_service
    container_name: order-service
    depends_on:
      - discovery_server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery_server:8761/eureka
      MONGODB_URI: mongodb+srv://nothi:129837465lg@cluster0.na3zkcc.mongodb.net/work_order_db?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - mechanic-net

  db_principal:
    image: guillermopalacios/mysql_data
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 129837465lg
      MYSQL_DATABASE: principal_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - principal-net

volumes:
  mysql_data:

networks:
  mechanic-net:
    driver: bridge
  principal-net:
    driver: bridge