version: '3.8'
name: microservice_app
services:
  angular-front:
    image: guillermopalacios/angular-mechanic
    container_name: front_app
    ports:
      - "4200:80"
    networks:
      - mechanic-net
    
  discovery-server:
    image: guillermopalacios/microservice_mechanic_discovery_server
    container_name: discovery_server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    ports:
      - "8761:8761"
    depends_on:
      - angular-front
    networks:
      - mechanic-net

  api-gateway:
    image: guillermopalacios/microservice_mechanic_api_gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      URL_FRONT: http://localhost:4200
    networks:
      - mechanic-net

  principal-service:
    image: guillermopalacios/microservice_mechanic_principal_service
    container_name: principal_service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db_principal:3306/principal_db
      URL_FRONT: http://localhost:4200
    depends_on:
      - db_principal
      - discovery-server
    networks:
      - principal-net
      - mechanic-net

  order-service:
    image: guillermopalacios/microservice_mechanic_order_service
    container_name: order_service
    depends_on:
      - discovery-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      MONGODB_URI: mongodb+srv://nothi:129837465lg@cluster0.na3zkcc.mongodb.net/work_order_db?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - mechanic-net

  db_principal:
    image: guillermopalacios/mysql_data
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 129837465lg
      MYSQL_DATABASE: principal_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - principal-net

volumes:
  mysql_data:

networks:
  mechanic-net:
    driver: bridge
  principal-net:
    driver: bridge